version: "3"
networks:
  development:
volumes:
  db_data:
  gem_cache:
  shared_data:
services:
  active_admin_sample_redis:
    image: redis:4.0-alpine
    command: redis-server
    networks:
      - development
    volumes:
      - shared_data:/var/shared/redis
  active_admin_sample_db:
    image: postgres:12.5-alpine
    container_name: active_admin_sample_db
    volumes:
      - db_data:/var/lib/postgresql/data
      - shared_data:/var/shared
    networks:
      - development
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - 5099:5432
  active_admin_sample:
    build:
      context: ./.active_admin_sample
      dockerfile: Dockerfile
    container_name: active_admin_sample
    volumes:
      - ./.active_admin_sample:/var/app
      - ./:/active_admin_kubik
      - ${ELEMENTS_PATH}:/kubik_styles_base
      - shared_data:/var/shared
      - gem_cache:/usr/local/bundle/gems
    networks:
      - development
    ports:
      - 3000:3000
    stdin_open: true
    tty: true
    env_file: ./.active_admin_sample/.env.development-local-elements
    entrypoint: dev-entrypoint.sh
    command: ['bundle', 'exec', 'rails', 'server', '-p', '3000', '-b', '0.0.0.0']
    environment:
      RAILS_ENV: development
    depends_on:
      - active_admin_sample_db
